import { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { api } from '../../../lib/api';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { Textarea } from '../../components/ui/textarea';
import { toast } from 'sonner';
import { Plus, Edit, FileText, Loader2, CheckCircle, AlertCircle, Trash2, Printer, ChevronDown, ChevronUp, ImagePlus, X } from 'lucide-react';
import { ErrorBoundary } from '../../components/ErrorBoundary';

// ─── Types ──────────────────────────────────────────────────────────────────

interface Question {
    id: string;
    type: 'text' | 'mcq' | 'short' | 'long';
    text: string;
    marks: number | '';
    optionA: string;
    optionB: string;
    optionC: string;
    optionD: string;
    imageUrl?: string;
}

interface SectionState {
    sectionId: string;
    sectionName: string;
    sectionTitle: string;
    totalMarks: number;
    questions: Question[];
}

const emptyQuestion = (): Question => ({
    id: `q-${Date.now()}-${Math.random()}`,
    type: 'text',
    text: '',
    marks: '',
    optionA: '',
    optionB: '',
    optionC: '',
    optionD: '',
    imageUrl: '',
});

// ─── Print HTML Generator ────────────────────────────────────────────────────

function generateExamPaperHTML(opts: {
    schoolName: string;
    schoolAddress: string;
    schoolPhone: string;
    paperTitle: string;
    examType: string;
    className: string;
    subjectName: string;
    maxMarks: number;
    duration: number;
    sections: SectionState[];
    provideAnswerSpace: boolean;
}) {
    const { schoolName, schoolAddress, schoolPhone, paperTitle, examType, className, subjectName, maxMarks, duration, sections, provideAnswerSpace } = opts;

    const sectionsHTML = sections.map(sec => {
        if (sec.questions.length === 0) return '';

        const qHTML = sec.questions.map((q, qi) => {
            let answerSpace = '';
            if (q.type === 'mcq') {
                answerSpace = `
                <ul class="mcq-options">
                    <li data-opt="A">${q.optionA || '_____________________'}</li>
                    <li data-opt="B">${q.optionB || '_____________________'}</li>
                    <li data-opt="C">${q.optionC || '_____________________'}</li>
                    <li data-opt="D">${q.optionD || '_____________________'}</li>
                </ul>`;
            } else if (provideAnswerSpace) {
                if (q.type === 'short') {
                    answerSpace = `
                    <div class="answer-lines">
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                    </div>`;
                } else if (q.type === 'long') {
                    answerSpace = `
                    <div class="writing-box tall"></div>`;
                } else {
                    answerSpace = `
                    <div class="answer-lines"><div class="line"></div></div>`;
                }
            }

            const imgHTML = q.imageUrl ? `<div class="diagram-frame"><img src="${q.imageUrl}" style="max-width:100%; max-height:200px;" /><div class="diagram-caption">Image Reference</div></div>` : '';

            return `
            <div class="question-block avoid-break">
                <div class="q-row">
                    <span class="q-num">${qi + 1}.</span>
                    <span class="q-text">${q.text || '_________________________________________________'}</span>
                    <span class="q-marks">[${q.marks}]</span>
                </div>
                ${imgHTML}
                ${answerSpace}
            </div>`;
        }).join('');

        const sectionTotal = sec.questions.reduce((s, q) => s + (Number(q.marks) || 0), 0);
        return `
        <div class="section-heading avoid-break">
            <span class="sec-label">SECTION ${sec.sectionName}</span>
            <span class="sec-sub">${sec.sectionTitle || 'Questions'} (${sec.questions.length} &times; ${sec.questions[0]?.marks || 1} = ${sectionTotal} Marks)</span>
        </div>
        ${qHTML}`;
    }).join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${paperTitle} — Kautix School ERP</title>
<meta name="description" content="Print-ready CBSE/ICSE style examination paper template generated by Kautix School ERP">

<style>
/* ==========================================================================
   1. CSS VARIABLES / DESIGN TOKENS
   ========================================================================== */
:root{
  --ink:#111111;
  --ink-soft:#333333;
  --line:#000000;
  --line-soft:#666666;
  --paper:#ffffff;
  --grey-bg:#f4f4f4;
  --font-main:"Times New Roman", Times, serif;
  --page-w:210mm;
  --page-h:297mm;
  --margin:14mm;
  --radius:2px;
}

* { box-sizing:border-box; }

html,body{
  margin:0;
  padding:0;
  background:var(--grey-bg);
  font-family:var(--font-main);
  color:var(--ink);
}

/* ==========================================================================
   2. PAGE / PRINT SETUP
   ========================================================================== */
@page{
  size:A4;
  margin: 14mm 14mm 18mm 14mm;
}

.sheet{
  width:var(--page-w);
  min-height:var(--page-h);
  margin:10mm auto;
  padding:var(--margin);
  background:var(--paper);
  box-shadow:0 0 8px rgba(0,0,0,0.15);
  position:relative;
}

@media print{
  html,body{ background:var(--paper); }
  .sheet{
    width:auto;
    min-height:auto;
    margin:0;
    padding:0;
    box-shadow:none;
  }
  .no-print{ display:none !important; }
  .page-break{ page-break-before:always; break-before:page; }
  .avoid-break{ page-break-inside:avoid; break-inside:avoid; }
  table{ page-break-inside:avoid; }
  .question-block{ page-break-inside:avoid; break-inside:avoid; }
  .footer-block{ page-break-inside:avoid; }
}

/* ==========================================================================
   3. TYPOGRAPHY BASE
   ========================================================================== */
body, .sheet{ font-size:12.5pt; line-height:1.5; }
h1,h2,h3,h4{ margin:0; font-family:var(--font-main); }
p{ margin:0 0 6px 0; }

.divider{
  border:none;
  border-top:1.5px solid var(--line);
  margin:8px 0;
}
.divider.thin{ border-top-width:0.75px; margin:6px 0; }

/* ==========================================================================
   4. HEADER
   ========================================================================== */
.exam-header{ text-align:center; }
.school-name{
  font-size:22pt;
  font-weight:700;
  letter-spacing:0.5px;
  text-transform:uppercase;
}
.school-meta{
  font-size:10.5pt;
  color:var(--ink-soft);
  margin-top:2px;
}
.school-meta span::after{
  content:"  |  ";
  color:var(--line-soft);
}
.school-meta span:last-child::after{ content:""; }

.board-recognition{
  font-size:9.5pt;
  font-style:italic;
  color:var(--ink-soft);
  margin-top:2px;
}

.exam-title{
  text-align:center;
  margin-top:6px;
}
.exam-title .title-main{
  font-size:15pt;
  font-weight:700;
  text-transform:uppercase;
  letter-spacing:1px;
}
.exam-title .title-sub{
  font-size:11pt;
  margin-top:2px;
}

/* ==========================================================================
   5. EXAM DETAILS TABLE
   ========================================================================== */
table.details-table{
  width:100%;
  border-collapse:collapse;
  margin-top:8px;
  font-size:11pt;
}
table.details-table td{
  border:1px solid var(--line);
  padding:5px 8px;
}
table.details-table td.label{
  font-weight:700;
  background:var(--grey-bg);
  width:22%;
}
table.details-table td.value{
  width:28%;
}

/* ==========================================================================
   6. STUDENT DETAILS
   ========================================================================== */
.student-details{
  margin-top:10px;
  border:1.5px solid var(--line);
  padding:8px 12px;
}
.student-details .row{
  display:flex;
  justify-content:space-between;
  flex-wrap:wrap;
  gap:6px 18px;
  font-size:11pt;
}
.student-details .field{
  flex:1 1 45%;
  white-space:nowrap;
}
.fill-line{
  display:inline-block;
  border-bottom:1px solid var(--line);
  min-width:120px;
  height:14px;
  vertical-align:bottom;
}
.signature-box{
  margin-top:6px;
  text-align:right;
  font-size:11pt;
}

/* ==========================================================================
   7. INSTRUCTIONS
   ========================================================================== */
.instructions{
  margin-top:10px;
  border:1px solid var(--line);
  padding:8px 14px;
}
.instructions h3{
  font-size:11.5pt;
  text-decoration:underline;
  margin-bottom:6px;
  text-align:center;
}
.instructions ol{
  margin:0;
  padding-left:18px;
  font-size:10.5pt;
}
.instructions li{ margin-bottom:3px; }

/* ==========================================================================
   8. SECTIONS
   ========================================================================== */
.section-heading{
  margin-top:16px;
  text-align:center;
  border-top:2px solid var(--line);
  border-bottom:2px solid var(--line);
  padding:5px 0;
}
.section-heading .sec-label{
  font-size:13pt;
  font-weight:700;
  text-transform:uppercase;
  letter-spacing:1px;
}
.section-heading .sec-sub{
  font-size:10.5pt;
  font-style:italic;
  display:block;
  margin-top:2px;
}

.question-block{
  margin-top:12px;
}
.sheet.compact-mode .question-block{
  margin-top:4px;
}
.q-row{
  display:flex;
  gap:6px;
  font-size:11.5pt;
  align-items:flex-start;
}
.q-num{
  font-weight:700;
  min-width:26px;
}
.q-text{ flex:1; }
.q-marks{
  font-weight:700;
  white-space:nowrap;
  margin-left:8px;
}

/* MCQ options */
.mcq-options{
  list-style:none;
  margin:6px 0 0 32px;
  padding:0;
  display:grid;
  grid-template-columns:1fr 1fr;
  gap:4px 20px;
  font-size:11pt;
}
.mcq-options li::before{
  content:attr(data-opt) ") ";
  font-weight:700;
  margin-right:4px;
}

/* Answer lines */
.answer-lines{ margin:8px 0 0 32px; }
.answer-lines .line{
  border-bottom:1px solid var(--line-soft);
  height:20px;
}

/* Writing box */
.writing-box{
  margin:8px 0 0 32px;
  border:1px solid var(--line);
  height:70px;
}
.writing-box.tall{ height:130px; }

/* Grid / graph paper */
.grid-box{
  margin:8px 0 0 32px;
  border:1px solid var(--line);
  height:110px;
  background-image:
    linear-gradient(to right, #ccc 1px, transparent 1px),
    linear-gradient(to bottom, #ccc 1px, transparent 1px);
  background-size:8mm 8mm;
}

/* Match the following */
table.match-table{
  margin:8px 0 0 32px;
  border-collapse:collapse;
  width:calc(100% - 32px);
  font-size:11pt;
}
table.match-table th, table.match-table td{
  border:1px solid var(--line);
  padding:4px 8px;
  text-align:left;
}
table.match-table th{ background:var(--grey-bg); }

/* Case study box */
.case-study{
  margin:8px 0 0 32px;
  border:1px solid var(--line);
  padding:8px 10px;
  background:#fafafa;
  font-size:10.5pt;
}
.case-study .passage-title{
  font-weight:700;
  text-decoration:underline;
  margin-bottom:4px;
  display:block;
}

/* Diagram frame */
.diagram-frame{
  margin:8px auto 0 32px;
  border:1px solid var(--line-soft);
  padding:8px;
  display:inline-block;
  text-align:center;
}
.diagram-caption{
  font-size:9.5pt;
  font-style:italic;
  margin-top:4px;
}

/* ==========================================================================
   9. FOOTER
   ========================================================================== */
.footer-block{
  margin-top:26px;
  border-top:1.5px solid var(--line);
  padding-top:8px;
}
.footer-signatures{
  display:flex;
  justify-content:space-between;
  margin-top:24px;
  font-size:10.5pt;
}
.footer-signatures .sig{
  text-align:center;
  width:22%;
}
.footer-signatures .sig .line{
  border-top:1px solid var(--line);
  margin-top:26px;
  padding-top:3px;
}
.footer-meta{
  display:flex;
  justify-content:space-between;
  margin-top:14px;
  font-size:9pt;
  color:var(--ink-soft);
}
.page-number::after{
  content: "Page " counter(page);
}

/* Screen-only toolbar */
.toolbar{
  max-width:var(--page-w);
  margin:10px auto 0 auto;
  text-align:center;
  font-family:Arial, sans-serif;
}
.toolbar button{
  font-family:Arial, sans-serif;
  padding:12px 24px;
  font-size:12pt;
  cursor:pointer;
  background: #2563eb;
  color: white;
  border: none;
  border-radius: 4px;
  font-weight: bold;
}
</style>
</head>
<body>

<!-- Screen-only print helper -->
<div class="toolbar no-print">
  <button onclick="window.print()">🖨️ Print / Save as PDF</button>
</div>

<div class="sheet ${!provideAnswerSpace ? 'compact-mode' : ''}">

  <!-- HEADER -->
  <header class="exam-header">
    <div class="school-name">${schoolName || 'YOUR SCHOOL NAME'}</div>
    <div class="school-meta">
      <span>${schoolAddress || 'School Address Line 1'}</span>
      <span>Ph: ${schoolPhone || 'N/A'}</span>
    </div>

    <hr class="divider">

    <div class="exam-title">
      <div class="title-main">${examType.toUpperCase()}</div>
      <div class="title-sub">${paperTitle}</div>
    </div>

    <hr class="divider thin">
  </header>

  <!-- EXAM DETAILS TABLE -->
  <table class="details-table avoid-break">
    <tbody>
      <tr>
        <td class="label">Subject</td><td class="value">${subjectName}</td>
        <td class="label">Class</td><td class="value">${className}</td>
      </tr>
      <tr>
        <td class="label">Exam Date</td><td class="value">____ / ____ / ______</td>
        <td class="label">Duration</td><td class="value">${duration} Hours</td>
      </tr>
      <tr>
        <td class="label">Maximum Marks</td><td class="value">${maxMarks}</td>
        <td class="label">Passing Marks</td><td class="value">${Math.floor(maxMarks * 0.35)}</td>
      </tr>
    </tbody>
  </table>

  <!-- STUDENT DETAILS -->
  <section class="student-details avoid-break">
    <div class="row">
      <div class="field">Student Name: <span class="fill-line" style="min-width:220px;"></span></div>
      <div class="field">Admission No.: <span class="fill-line" style="min-width:150px;"></span></div>
    </div>
    <div class="row" style="margin-top:6px;">
      <div class="field">Roll Number: <span class="fill-line" style="min-width:150px;"></span></div>
      <div class="field">Teacher Sign: <span class="fill-line" style="min-width:150px;"></span></div>
    </div>
  </section>

  <!-- GENERAL INSTRUCTIONS -->
  <section class="instructions avoid-break">
    <h3>General Instructions</h3>
    <ol>
      <li>Read all questions carefully before answering.</li>
      <li>All questions are compulsory unless specified.</li>
      <li>Write neatly using blue or black pen.</li>
      <li>Show complete working wherever required.</li>
      <li>Draw diagrams wherever necessary.</li>
      <li>Do not write in the margins.</li>
    </ol>
  </section>

  <!-- SECTIONS -->
  ${sectionsHTML}

  <!-- FOOTER -->
  <footer class="footer-block avoid-break">
    <div class="footer-signatures">
      <div class="sig"><div class="line">Teacher Signature</div></div>
      <div class="sig"><div class="line">Checked By</div></div>
      <div class="sig"><div class="line">Exam Controller</div></div>
      <div class="sig"><div class="line">Principal Signature</div></div>
    </div>
    <div class="footer-meta">
      <span>Generated on: ${new Date().toLocaleDateString('en-IN')}</span>
      <span class="page-number"></span>
      <span>Generated using Kautix School ERP &middot; www.kautix.in</span>
    </div>
  </footer>

</div>

</body>
</html>`;
}

// ─── Question Row ────────────────────────────────────────────────────────────

function QuestionRow({ q, idx, onChange, onDelete }: {
    q: Question; idx: number;
    onChange: (field: keyof Question, val: any) => void;
    onDelete: () => void;
}) {
    const [expanded, setExpanded] = useState(true);

    const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;
        try {
            const reader = new FileReader();
            reader.onload = async (ev) => {
                const dataUrl = ev.target?.result as string;
                try {
                    const res = await api.uploadExamPaperImage(dataUrl, file.name, 'question-images');
                    onChange('imageUrl', res.url);
                    toast.success('Image uploaded to S3');
                } catch (err: any) {
                    toast.error(err.message || 'Failed to upload image');
                }
            };
            reader.readAsDataURL(file);
        } catch (err: any) {
            toast.error('Failed to read image file');
        }
    };
    return (
        <div className="border rounded-lg bg-white shadow-sm">
            {/* Row header */}
            <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 rounded-t-lg border-b">
                <span className="text-sm font-semibold text-gray-500 w-6">{idx + 1}.</span>
                <Select value={q.type} onValueChange={v => onChange('type', v)}>
                    <SelectTrigger className="w-24 h-7 text-xs"><SelectValue /></SelectTrigger>
                    <SelectContent>
                        <SelectItem value="text">1 Line</SelectItem>
                        <SelectItem value="short">Short</SelectItem>
                        <SelectItem value="long">Long</SelectItem>
                        <SelectItem value="mcq">MCQ</SelectItem>
                    </SelectContent>
                </Select>
                <Input
                    type="number"
                    value={q.marks === '' ? '' : q.marks}
                    onChange={e => onChange('marks', e.target.value === '' ? '' : parseInt(e.target.value))}
                    className="w-20 h-7 text-xs"
                    placeholder="Marks"
                />
                <span className="text-xs text-gray-400">marks</span>
                <div className="flex-1" />
                <label className="cursor-pointer">
                    <input type="file" className="hidden" accept="image/*" onChange={handleImageUpload} />
                    <Button variant="ghost" size="sm" className="h-6 px-2 text-xs" asChild>
                        <span><ImagePlus className="w-3 h-3 mr-1" /> Image</span>
                    </Button>
                </label>
                <Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setExpanded(e => !e)}>
                    {expanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                </Button>
                <Button variant="ghost" size="sm" className="h-6 w-6 p-0 text-red-400 hover:text-red-600" onClick={onDelete}>
                    <Trash2 className="w-3 h-3" />
                </Button>
            </div>

            {expanded && (
                <div className="px-3 py-3 space-y-2">
                    {q.imageUrl && (
                        <div className="relative inline-block border rounded-md p-1 mb-2">
                            <img src={q.imageUrl} alt="preview" className="h-20 object-contain" />
                            <button
                                onClick={() => onChange('imageUrl', '')}
                                className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-0.5 hover:bg-red-600 shadow"
                                title="Remove Image"
                            >
                                <X className="w-3 h-3" />
                            </button>
                        </div>
                    )}
                    <Textarea
                        value={q.text}
                        onChange={e => onChange('text', e.target.value)}
                        placeholder="Enter question text…"
                        rows={2}
                        className="text-sm resize-y"
                    />
                    {q.type === 'mcq' && (
                        <div className="grid grid-cols-2 gap-2">
                            {(['A', 'B', 'C', 'D'] as const).map(opt => (
                                <div key={opt} className="flex items-center gap-1.5">
                                    <span className="text-xs font-bold text-blue-600 w-4">({opt})</span>
                                    <Input
                                        value={(q as any)[`option${opt}`]}
                                        onChange={e => onChange(`option${opt}` as keyof Question, e.target.value)}
                                        placeholder={`Option ${opt}`}
                                        className="h-7 text-xs flex-1"
                                    />
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}

// ─── Section Panel ───────────────────────────────────────────────────────────

function SectionPanel({ sec, onChange }: { sec: SectionState; onChange: (s: SectionState) => void }) {
    const addQ = () => onChange({ ...sec, questions: [...sec.questions, emptyQuestion()] });
    const updateQ = (i: number, field: keyof Question, val: any) => {
        const qs = [...sec.questions];
        qs[i] = { ...qs[i], [field]: val };
        onChange({ ...sec, questions: qs });
    };
    const deleteQ = (i: number) => onChange({ ...sec, questions: sec.questions.filter((_, idx) => idx !== i) });

    const totalMarksAdded = sec.questions.reduce((s, q) => s + (Number(q.marks) || 0), 0);
    const ok = totalMarksAdded === sec.totalMarks;
    const over = totalMarksAdded > sec.totalMarks;

    return (
        <Card className="border-2">
            <CardHeader className="pb-2 pt-3 px-4">
                <div className="flex items-center justify-between flex-wrap gap-2">
                    <div>
                        <CardTitle className="text-base">
                            Section {sec.sectionName}: {sec.sectionTitle || 'Questions'}
                        </CardTitle>
                        <p className="text-xs text-gray-500 mt-0.5">Section max marks: <strong>{sec.totalMarks}</strong></p>
                    </div>
                    <div className="flex items-center gap-2">
                        <Badge className={ok ? 'bg-green-600' : over ? 'bg-red-500 text-white' : 'bg-gray-200 text-gray-700'}>
                            {totalMarksAdded} / {sec.totalMarks} marks
                        </Badge>
                        <Badge variant="outline">{sec.questions.length} Qs</Badge>
                        <Button size="sm" variant="outline" onClick={addQ} className="h-7 text-xs">
                            <Plus className="w-3 h-3 mr-1" /> Add Question
                        </Button>
                    </div>
                </div>
            </CardHeader>
            <CardContent className="px-4 pb-4 space-y-2">
                {sec.questions.length === 0 ? (
                    <div className="text-center py-6 text-gray-400 text-sm border-2 border-dashed rounded-lg">
                        <p>No questions yet</p>
                        <p className="text-xs mt-1">Click "Add Question" to start adding questions to this section</p>
                    </div>
                ) : (
                    sec.questions.map((q, i) => (
                        <QuestionRow
                            key={q.id}
                            q={q}
                            idx={i}
                            onChange={(f, v) => updateQ(i, f, v)}
                            onDelete={() => deleteQ(i)}
                        />
                    ))
                )}
            </CardContent>
        </Card>
    );
}

// ─── Create Paper Modal ──────────────────────────────────────────────────────

function CreatePaperModal({ template, open, onClose, onSaved, user, existingPaper }: {
    template: any;
    open: boolean;
    onClose: () => void;
    onSaved: () => void;
    user: any;
    existingPaper?: any;
}) {
    const rawSections: any[] = (template?.sections || []).sort(
        (a: any, b: any) => (a.section_order || 0) - (b.section_order || 0)
    );
    const effectiveSections = rawSections.length > 0 ? rawSections : [
        { id: 'default', section_name: 'A', section_title: 'Questions', total_marks: template?.total_marks || 100 }
    ];

    const [paperTitle, setPaperTitle] = useState('');
    const [examType, setExamType] = useState('midterm');
    const [provideAnswerSpace, setProvideAnswerSpace] = useState(true);
    const [sectionStates, setSectionStates] = useState<SectionState[]>([]);
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        if (open) {
            if (existingPaper) {
                // Pre-load from saved paper
                setPaperTitle(existingPaper.title || '');
                setExamType(existingPaper.exam_type || 'midterm');
                // Rebuild sectionStates from saved questions
                const secMap = new Map<string, SectionState>();
                effectiveSections.forEach(s => {
                    secMap.set(s.id, {
                        sectionId: s.id,
                        sectionName: s.section_name,
                        sectionTitle: s.section_title || '',
                        totalMarks: s.total_marks || 0,
                        questions: [],
                    });
                });
                if (!secMap.size) {
                    secMap.set('default', { sectionId: 'default', sectionName: 'A', sectionTitle: 'Questions', totalMarks: template?.total_marks || 0, questions: [] });
                }
                (existingPaper.questions || []).sort((a: any, b: any) => (a.question_order || 0) - (b.question_order || 0)).forEach((pq: any) => {
                    const sId = pq.section_id || 'default';
                    let sec = secMap.get(sId);
                    if (!sec) {
                        const first = secMap.values().next().value;
                        sec = first || { sectionId: 'default', sectionName: 'A', sectionTitle: 'Questions', totalMarks: 0, questions: [] };
                    }
                    sec.questions.push({
                        id: pq.question_id || `inline-${Date.now()}-${Math.random()}`,
                        type: pq.question_type || pq.question?.type || 'short',
                        text: pq.custom_question_text || pq.question?.question_text || '',
                        marks: pq.custom_marks ?? 1,
                        imageUrl: pq.image_url || pq.question?.image_url || null,
                        optionA: pq.options?.A || pq.question?.options?.A || '',
                        optionB: pq.options?.B || pq.question?.options?.B || '',
                        optionC: pq.options?.C || pq.question?.options?.C || '',
                        optionD: pq.options?.D || pq.question?.options?.D || '',
                    });
                });
                setSectionStates(Array.from(secMap.values()));
            } else {
                setPaperTitle('');
                setExamType('midterm');
                setSectionStates(effectiveSections.map(s => ({
                    sectionId: s.id,
                    sectionName: s.section_name,
                    sectionTitle: s.section_title || '',
                    totalMarks: s.total_marks || 0,
                    questions: [],
                })));
            }
        }
    }, [open]);

    const totalQs = sectionStates.reduce((s, sec) => s + sec.questions.length, 0);
    const totalMarksAdded = sectionStates.reduce((s, sec) => s + sec.questions.reduce((ss, q) => ss + (Number(q.marks) || 0), 0), 0);
    const maxMarks = template?.total_marks || 0;
    const marksMatch = totalMarksAdded === maxMarks;
    const marksOver = totalMarksAdded > maxMarks;

    const handlePrint = () => {
        const html = generateExamPaperHTML({
            schoolName: user?.school || 'Your School',
            schoolAddress: user?.schoolAddress || '',
            schoolPhone: user?.schoolPhone || '',
            paperTitle: paperTitle || template?.name || 'Exam Paper',
            examType,
            className: template?.class?.name || '',
            subjectName: template?.subject?.name || '',
            maxMarks,
            duration: template?.duration_minutes || 180,
            sections: sectionStates,
            provideAnswerSpace
        });
        const w = window.open('', '_blank', 'width=900,height=700');
        if (w) { w.document.write(html); w.document.close(); }
    };

    const handleSave = async () => {
        if (!paperTitle.trim()) { toast.error('Please enter a paper title'); return; }
        if (totalQs === 0) { toast.error('Please add at least one question'); return; }
        if (!marksMatch) {
            toast.error(`Total marks (${totalMarksAdded}) must equal max marks (${maxMarks})`);
            return;
        }
        setSaving(true);
        try {
            const allQuestions: any[] = [];
            sectionStates.forEach(sec => {
                sec.questions.forEach((q, qi) => {
                    allQuestions.push({
                        questionId: q.id,
                        sectionId: sec.sectionId === 'default' ? null : sec.sectionId,
                        questionOrder: allQuestions.length + 1,
                        customMarks: q.marks,
                        customQuestionText: q.text,
                        questionType: q.type,
                        imageUrl: q.imageUrl || null,
                        options: q.type === 'mcq' ? { A: q.optionA, B: q.optionB, C: q.optionC, D: q.optionD } : null,
                    });
                });
            });

            if (existingPaper) {
                // Update existing paper
                await api.updateExamPaper(existingPaper.id, {
                    paperTitle,
                    examType,
                    totalMarks: totalMarksAdded,
                    questions: allQuestions,
                    status: existingPaper.status || 'draft',
                });
                toast.success('Paper updated successfully!');
            } else {
                await api.createExamPaper({
                    templateId: template.id,
                    paperCode: `${paperTitle.replace(/\s+/g, '-').toUpperCase()}-${Date.now()}`,
                    paperTitle,
                    examType,
                    totalMarks: totalMarksAdded,
                    durationMinutes: template.duration_minutes || 180,
                    questions: allQuestions,
                    status: 'draft',
                });
                toast.success('Exam paper created successfully!');
            }
            onSaved();
            onClose();
        } catch (err: any) {
            toast.error(err.message || 'Failed to save paper');
        } finally {
            setSaving(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onClose}>
            <DialogContent className="max-w-4xl max-h-[94vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="text-xl">{existingPaper ? 'Edit Paper' : 'Create Paper'} — {template?.name}</DialogTitle>
                    <p className="text-sm text-gray-500">
                        {template?.class?.name} · {template?.subject?.name} · {template?.total_marks} Marks · {template?.duration_minutes} mins
                    </p>
                </DialogHeader>

                <div className="space-y-5 py-2">
                    {/* Meta */}
                    <div className="flex items-center space-x-2 pb-2">
                        <input type="checkbox" id="provideSpace" checked={provideAnswerSpace} onChange={e => setProvideAnswerSpace(e.target.checked)} className="rounded border-gray-300 w-4 h-4" />
                        <label htmlFor="provideSpace" className="text-sm font-medium text-gray-700 cursor-pointer">Provide space for answers in print (lines/boxes)</label>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                            <Label>Paper Title *</Label>
                            <Input value={paperTitle} onChange={e => setPaperTitle(e.target.value)} placeholder="e.g., Mid-Term Mathematics 2025" />
                        </div>
                        <div className="space-y-2">
                            <Label>Exam Type</Label>
                            <Select value={examType} onValueChange={setExamType}>
                                <SelectTrigger><SelectValue /></SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="midterm">Mid-Term</SelectItem>
                                    <SelectItem value="final">Final Exam</SelectItem>
                                    <SelectItem value="unit">Unit Test</SelectItem>
                                    <SelectItem value="quarterly">Quarterly</SelectItem>
                                    <SelectItem value="annual">Annual</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </div>

                    {/* Sections with questions */}
                    <div className="space-y-4">
                        <div className="flex items-center gap-2">
                            <FileText className="w-4 h-4 text-blue-600" />
                            <span className="font-semibold">Questions by Section</span>
                            <span className="text-xs text-gray-400">— Add Text or MCQ questions. Set marks per question.</span>
                        </div>
                        {sectionStates.map((sec, i) => (
                            <SectionPanel
                                key={sec.sectionId}
                                sec={sec}
                                onChange={updated => {
                                    const copy = [...sectionStates];
                                    copy[i] = updated;
                                    setSectionStates(copy);
                                }}
                            />
                        ))}
                    </div>

                    {/* Summary bar */}
                    <div className={`rounded-xl p-4 flex items-center justify-between border-2 ${marksMatch ? 'bg-green-50 border-green-200' :
                        marksOver ? 'bg-red-50 border-red-200' :
                            'bg-blue-50 border-blue-200'
                        }`}>
                        <div className="flex items-center gap-3">
                            {marksMatch
                                ? <CheckCircle className="w-5 h-5 text-green-600" />
                                : <AlertCircle className={`w-5 h-5 ${marksOver ? 'text-red-500' : 'text-blue-500'}`} />
                            }
                            <div>
                                <p className="font-semibold text-sm">
                                    {marksMatch ? 'Ready to save! Total marks match.' :
                                        marksOver ? `Over by ${totalMarksAdded - maxMarks} marks — reduce marks` :
                                            `${maxMarks - totalMarksAdded} marks remaining`}
                                </p>
                                <p className="text-xs text-gray-500 mt-0.5">{totalQs} questions · {totalMarksAdded} / {maxMarks} marks</p>
                            </div>
                        </div>
                        <div className="text-right">
                            <p className="text-2xl font-bold">{totalMarksAdded}<span className="text-sm text-gray-400 font-normal"> / {maxMarks}</span></p>
                        </div>
                    </div>
                </div>

                <DialogFooter className="gap-2">
                    <Button variant="outline" onClick={onClose}>Cancel</Button>
                    <Button variant="outline" onClick={handlePrint} disabled={totalQs === 0}>
                        <Printer className="w-4 h-4 mr-2" />Preview & Print
                    </Button>
                    <Button onClick={handleSave} disabled={saving || !marksMatch || totalQs === 0}>
                        {saving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <FileText className="w-4 h-4 mr-2" />}
                        {saving ? 'Saving…' : existingPaper ? 'Update Paper' : 'Save Paper'}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

function ExamTemplatesPageInner() {
    const { user } = useAuth();
    const isStaff = user?.role === 'admin' || user?.role === 'teacher';
    const [templates, setTemplates] = useState<any[]>([]);
    const [savedPapers, setSavedPapers] = useState<any[]>([]);
    const [activeTab, setActiveTab] = useState<'templates' | 'saved_papers'>('templates');
    const [classes, setClasses] = useState<any[]>([]);
    const [subjects, setSubjects] = useState<any[]>([]);
    const [academicYears, setAcademicYears] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const [modalOpen, setModalOpen] = useState(false);
    const [editingTemplate, setEditingTemplate] = useState<any>(null);

    useEffect(() => {
        if (editingTemplate) {
            setFormData({
                name: editingTemplate.name || '',
                classId: editingTemplate.class_id || '',
                subjectId: editingTemplate.subject_id || '',
                academicYearId: editingTemplate.academic_year_id || 'all',
                totalMarks: editingTemplate.total_marks?.toString() || '',
                durationMinutes: editingTemplate.duration_minutes?.toString() || '180',
                instructions: editingTemplate.instructions || '',
                generalInstructions: editingTemplate.general_instructions || '',
                sections: editingTemplate.exam_paper_sections?.length > 0
                    ? editingTemplate.exam_paper_sections.map((s: any) => ({
                        sectionName: s.section_name,
                        sectionTitle: s.section_title || '',
                        sectionOrder: s.section_order,
                        totalMarks: s.total_marks?.toString() || '',
                        instructions: s.instructions || ''
                    }))
                    : [{ sectionName: 'A', sectionTitle: 'Multiple Choice Questions', sectionOrder: 1, totalMarks: '', instructions: '' }]
            });
        } else {
            setFormData({
                name: '', classId: '', subjectId: '', academicYearId: 'all',
                totalMarks: '', durationMinutes: '180', instructions: '', generalInstructions: '',
                sections: [{ sectionName: 'A', sectionTitle: 'Multiple Choice Questions', sectionOrder: 1, totalMarks: '', instructions: '' }]
            });
        }
    }, [editingTemplate]);

    const handleDeleteTemplate = async (id: string) => {
        if (!confirm('Are you sure you want to delete this template?')) return;
        try {
            await api.deleteExamPaperTemplate(id);
            toast.success('Template deleted successfully');
            fetchData();
        } catch (err: any) {
            toast.error(err.message || 'Failed to delete template');
        }
    };

    const [formData, setFormData] = useState({
        name: '', classId: '', subjectId: '', academicYearId: 'all',
        totalMarks: '', durationMinutes: '180', instructions: '', generalInstructions: '',
        sections: [{ sectionName: 'A', sectionTitle: 'Multiple Choice Questions', sectionOrder: 1, totalMarks: '', instructions: '' }]
    });

    const [createPaperTemplate, setCreatePaperTemplate] = useState<any>(null);
    const [createPaperOpen, setCreatePaperOpen] = useState(false);
    const [editingPaper, setEditingPaper] = useState<any>(null);

    useEffect(() => {
        fetchData();
    }, []);

    const fetchData = async () => {
        try {
            setError(null);
            const [td, saved, cd, sd, yd] = await Promise.all([
                api.getExamPaperTemplates().catch(() => []),
                api.getExamPapers().catch(() => []),
                api.getClasses().catch(() => []),
                api.getSubjects().catch(() => []),
                api.getAcademicYears().catch(() => []),
            ]);
            setTemplates(Array.isArray(td) ? td : []);
            setSavedPapers(Array.isArray(saved) ? saved : []);
            setClasses(Array.isArray(cd) ? cd : []);
            setSubjects(Array.isArray(sd) ? sd : []);
            setAcademicYears(Array.isArray(yd) ? yd : []);
        } catch (err: any) {
            setError(err.message || 'Failed to load data');
        } finally {
            setLoading(false);
        }
    };

    const handleOpenSavedPaper = (paper: any) => {
        const sectionsMap = new Map<string, any>();
        const templateSections = paper.template?.sections || [];
        templateSections.forEach((ts: any) => {
            sectionsMap.set(ts.id, {
                sectionId: ts.id,
                sectionName: ts.section_name,
                sectionTitle: ts.section_title || '',
                totalMarks: ts.total_marks,
                instructions: ts.instructions || '',
                questions: []
            });
        });
        if (paper.questions) {
            paper.questions.forEach((pq: any) => {
                const sId = pq.section_id || 'default';
                let sec = sectionsMap.get(sId);
                if (!sec) {
                    sec = { sectionId: 'default', sectionName: 'A', sectionTitle: 'Questions', totalMarks: 0, instructions: '', questions: [] };
                    sectionsMap.set('default', sec);
                }
                sec.questions.push({
                    id: pq.question_id,
                    type: pq.question_type || pq.question?.type || 'short',
                    text: pq.custom_question_text || pq.question?.question_text || '',
                    marks: pq.custom_marks || 1,
                    imageUrl: pq.image_url || pq.question?.image_url || null,
                    optionA: pq.options?.A || pq.question?.options?.A || '',
                    optionB: pq.options?.B || pq.question?.options?.B || '',
                    optionC: pq.options?.C || pq.question?.options?.C || '',
                    optionD: pq.options?.D || pq.question?.options?.D || '',
                });
            });
        }
        const sectionStates = Array.from(sectionsMap.values());
        const html = generateExamPaperHTML({
            schoolName: 'School',
            schoolAddress: '',
            schoolPhone: '',
            paperTitle: paper.title || paper.template?.name || 'Exam Paper',
            examType: paper.template?.name || 'Examination',
            className: paper.exam?.class?.name || '',
            subjectName: paper.exam?.subject?.name || '',
            maxMarks: paper.total_marks || paper.template?.total_marks,
            duration: paper.duration_minutes || paper.template?.duration_minutes || 180,
            sections: sectionStates,
            provideAnswerSpace: true
        });
        const w = window.open('', '_blank', 'width=900,height=700');
        if (w) { w.document.write(html); w.document.close(); }
    };

    const handleSubmit = async () => {
        if (!formData.name || !formData.classId || !formData.subjectId || !formData.totalMarks) {
            toast.error('Please fill all required fields'); return;
        }
        try {
            if (editingTemplate) {
                await api.updateExamPaperTemplate(editingTemplate.id, {
                    name: formData.name, classId: formData.classId, subjectId: formData.subjectId,
                    academicYearId: formData.academicYearId === 'all' ? null : formData.academicYearId,
                    totalMarks: parseInt(formData.totalMarks),
                    durationMinutes: parseInt(formData.durationMinutes),
                    instructions: formData.instructions || null,
                    generalInstructions: formData.generalInstructions || null,
                    sections: formData.sections.map((s, i) => ({ ...s, sectionOrder: i + 1, totalMarks: parseInt(s.totalMarks) || 0 }))
                });
                toast.success('Template updated successfully');
            } else {
                await api.createExamPaperTemplate({
                    name: formData.name, classId: formData.classId, subjectId: formData.subjectId,
                    academicYearId: formData.academicYearId === 'all' ? null : formData.academicYearId,
                    totalMarks: parseInt(formData.totalMarks),
                    durationMinutes: parseInt(formData.durationMinutes),
                    instructions: formData.instructions || null,
                    generalInstructions: formData.generalInstructions || null,
                    sections: formData.sections.map((s, i) => ({ ...s, sectionOrder: i + 1, totalMarks: parseInt(s.totalMarks) || 0 }))
                });
                toast.success('Template created successfully');
            }
            setModalOpen(false);
            fetchData();
        } catch (err: any) { toast.error(err.message || 'Failed to save'); }
    };

    const addSection = () => {
        const n = formData.sections.length + 1;
        setFormData({ ...formData, sections: [...formData.sections, { sectionName: String.fromCharCode(64 + n), sectionTitle: '', sectionOrder: n, totalMarks: '', instructions: '' }] });
    };
    const updateSec = (i: number, f: string, v: string) => {
        const s = [...formData.sections]; s[i] = { ...s[i], [f]: v };
        setFormData({ ...formData, sections: s });
    };

    if (!isStaff) return <div className="flex items-center justify-center p-12"><Card className="border-red-200 bg-red-50"><CardContent className="pt-6"><p className="text-red-600 font-semibold">Access denied. Exam paper templates are only available to teachers and administrators.</p></CardContent></Card></div>;
    if (loading) return <div className="flex items-center justify-center p-12"><Loader2 className="w-6 h-6 animate-spin text-gray-400 mr-3" /><span className="text-gray-500">Loading…</span></div>;
    if (error) return <div className="p-6"><Card className="border-red-200 bg-red-50"><CardContent className="pt-6"><p className="text-red-600 font-semibold">{error}</p></CardContent></Card></div>;

    return (
        <div className="space-y-6 p-6">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold">Exam Papers</h1>
                    <p className="text-gray-500 mt-1">Manage templates and view saved exam papers</p>
                </div>
                {activeTab === 'templates' && (
                    <Button onClick={() => { setEditingTemplate(null); setModalOpen(true); }}>
                        <Plus className="w-4 h-4 mr-2" />Create Template
                    </Button>
                )}
            </div>

            <div className="flex border-b border-gray-200 -mt-2">
                <button
                    className={`py-2 px-5 border-b-2 font-medium text-sm transition-colors ${activeTab === 'templates' ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700'}`}
                    onClick={() => setActiveTab('templates')}
                >Paper Templates</button>
                <button
                    className={`py-2 px-5 border-b-2 font-medium text-sm transition-colors ${activeTab === 'saved_papers' ? 'border-primary text-primary' : 'border-transparent text-gray-500 hover:text-gray-700'}`}
                    onClick={() => setActiveTab('saved_papers')}
                >Saved Papers {savedPapers.length > 0 && <span className="ml-1 bg-primary text-white text-xs rounded-full px-1.5 py-0.5">{savedPapers.length}</span>}</button>
            </div>

            {activeTab === 'templates' && (
                templates.length === 0 ? (
                    <Card className="p-12 text-center">
                        <div className="text-gray-400">
                            <p className="text-lg mb-2">No exam paper templates yet</p>
                            <p className="text-sm mb-4">Create a template first to define the paper structure, then add questions to generate a printable exam paper.</p>
                            <Button onClick={() => { setEditingTemplate(null); setModalOpen(true); }}><Plus className="w-4 h-4 mr-2" />Create Template</Button>
                        </div>
                    </Card>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        {templates.map(template => (
                            <Card key={template.id} className="hover:shadow-lg transition-shadow">
                                <CardHeader>
                                    <div className="flex justify-between items-start">
                                        <CardTitle className="text-lg">{template.name || 'Untitled'}</CardTitle>
                                        <Badge>{template.total_marks || 0} Marks</Badge>
                                    </div>
                                    <p className="text-sm text-gray-500">{template.class?.name || '—'} · {template.subject?.name || '—'}</p>
                                </CardHeader>
                                <CardContent>
                                    <div className="space-y-2 text-sm mb-4">
                                        <div className="flex justify-between"><span className="text-gray-600">Duration:</span><span className="font-semibold">{template.duration_minutes} mins</span></div>
                                        <div className="flex justify-between"><span className="text-gray-600">Sections:</span><span className="font-semibold">{template.sections?.length || 0}</span></div>
                                        {template.sections?.length > 0 && (
                                            <div className="flex flex-wrap gap-1 mt-2">
                                                {template.sections.map((s: any) => (
                                                    <Badge key={s.id} variant="outline" className="text-xs">Sec {s.section_name}: {s.total_marks}m</Badge>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                    <div className="flex gap-2">
                                        <Button variant="outline" size="sm" className="flex-1" onClick={() => { setEditingTemplate(template); setModalOpen(true); }}>
                                            <Edit className="w-3 h-3 mr-1" />Edit
                                        </Button>
                                        <Button variant="outline" size="sm" className="text-red-600 hover:text-red-700 hover:bg-red-50" onClick={() => handleDeleteTemplate(template.id)}>
                                            <Trash2 className="w-3 h-3" />
                                        </Button>
                                        <Button size="sm" className="flex-1" onClick={() => { setCreatePaperTemplate(template); setCreatePaperOpen(true); }}>
                                            <FileText className="w-3 h-3 mr-1" />Create Paper
                                        </Button>
                                    </div>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                )
            )}

            {activeTab === 'saved_papers' && (
                savedPapers.length === 0 ? (
                    <Card className="p-12 text-center">
                        <div className="text-gray-400">
                            <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
                            <p className="text-lg mb-2">No saved papers yet</p>
                            <p className="text-sm">Papers you save from the Create Paper modal will appear here. Go to Paper Templates and click "Create Paper".</p>
                        </div>
                    </Card>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        {savedPapers.map(paper => (
                            <Card key={paper.id} className="hover:shadow-lg transition-shadow">
                                <CardHeader>
                                    <div className="flex justify-between items-start">
                                        <CardTitle className="text-base line-clamp-2">{paper.title || 'Untitled Paper'}</CardTitle>
                                        <Badge variant="outline" className="capitalize text-xs shrink-0 ml-2">{paper.status || 'draft'}</Badge>
                                    </div>
                                    <p className="text-sm text-gray-500">{paper.template?.name || '—'}</p>
                                </CardHeader>
                                <CardContent>
                                    <div className="space-y-1 text-sm mb-4">
                                        <div className="flex justify-between"><span className="text-gray-600">Max Marks:</span><span className="font-semibold">{paper.total_marks || paper.template?.total_marks || '—'}</span></div>
                                        <div className="flex justify-between"><span className="text-gray-600">Questions:</span><span className="font-semibold">{paper.questions?.length || 0}</span></div>
                                        <div className="flex justify-between"><span className="text-gray-600">Saved On:</span><span className="font-semibold">{new Date(paper.created_at).toLocaleDateString('en-IN')}</span></div>
                                    </div>
                                    <Button size="sm" className="w-full" onClick={() => handleOpenSavedPaper(paper)}>
                                        <Printer className="w-4 h-4 mr-2" />Open &amp; Print
                                    </Button>
                                    <Button variant="outline" size="sm" className="w-full mt-2" onClick={() => {
                                        const tpl = paper.template;
                                        if (tpl) { setCreatePaperTemplate(tpl); setEditingPaper(paper); setCreatePaperOpen(true); }
                                        else toast.error('Template data not available for this paper');
                                    }}>
                                        <Edit className="w-4 h-4 mr-2" />Edit Paper
                                    </Button>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                )
            )}

            {/* Template Modal */}
            <Dialog open={modalOpen} onOpenChange={setModalOpen}>
                <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
                    <DialogHeader>
                        <DialogTitle>{editingTemplate ? 'Edit Template' : 'Create Exam Paper Template'}</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-4 py-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2"><Label>Template Name *</Label><Input value={formData.name} onChange={e => setFormData({ ...formData, name: e.target.value })} placeholder="e.g., Mid-Term Mathematics" /></div>
                            <div className="space-y-2"><Label>Total Marks *</Label><Input type="number" value={formData.totalMarks} onChange={e => setFormData({ ...formData, totalMarks: e.target.value })} placeholder="100" /></div>
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2"><Label>Class *</Label>
                                <Select value={formData.classId} onValueChange={v => setFormData({ ...formData, classId: v })}>
                                    <SelectTrigger><SelectValue placeholder="Select class" /></SelectTrigger>
                                    <SelectContent>{classes.map((c: any) => <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent>
                                </Select>
                            </div>
                            <div className="space-y-2"><Label>Subject *</Label>
                                <Select value={formData.subjectId} onValueChange={v => setFormData({ ...formData, subjectId: v })}>
                                    <SelectTrigger><SelectValue placeholder="Select subject" /></SelectTrigger>
                                    <SelectContent>{subjects.map((s: any) => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent>
                                </Select>
                            </div>
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2"><Label>Academic Year</Label>
                                <Select value={formData.academicYearId} onValueChange={v => setFormData({ ...formData, academicYearId: v })}>
                                    <SelectTrigger><SelectValue /></SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="all">All Years</SelectItem>
                                        {academicYears.map((y: any) => <SelectItem key={y.id} value={y.id}>{y.name}</SelectItem>)}
                                    </SelectContent>
                                </Select>
                            </div>
                            <div className="space-y-2"><Label>Duration (minutes)</Label><Input type="number" value={formData.durationMinutes} onChange={e => setFormData({ ...formData, durationMinutes: e.target.value })} /></div>
                        </div>
                        <div className="space-y-2"><Label>General Instructions</Label><Textarea value={formData.generalInstructions} onChange={e => setFormData({ ...formData, generalInstructions: e.target.value })} placeholder="Enter general instructions…" rows={3} /></div>
                        <div className="space-y-3">
                            <div className="flex justify-between items-center">
                                <Label className="text-base font-semibold">Sections</Label>
                                <Button type="button" variant="outline" size="sm" onClick={addSection}><Plus className="w-3 h-3 mr-1" />Add Section</Button>
                            </div>
                            {formData.sections.map((sec, i) => (
                                <Card key={i} className="p-4">
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="space-y-2"><Label>Section Name</Label><Input value={sec.sectionName} onChange={e => updateSec(i, 'sectionName', e.target.value)} placeholder="A, B, C…" /></div>
                                        <div className="space-y-2"><Label>Section Title</Label><Input value={sec.sectionTitle} onChange={e => updateSec(i, 'sectionTitle', e.target.value)} placeholder="MCQ, Short Answer…" /></div>
                                        <div className="space-y-2"><Label>Total Marks</Label><Input type="number" value={sec.totalMarks} onChange={e => updateSec(i, 'totalMarks', e.target.value)} placeholder="20" /></div>
                                        <div className="space-y-2"><Label>Instructions (optional)</Label><Input value={sec.instructions} onChange={e => updateSec(i, 'instructions', e.target.value)} placeholder="Attempt all questions" /></div>
                                    </div>
                                </Card>
                            ))}
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
                        <Button onClick={handleSubmit}>Save Template</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* Create Paper Modal */}
            {createPaperTemplate && (
                <CreatePaperModal
                    template={createPaperTemplate}
                    open={createPaperOpen}
                    onClose={() => { setCreatePaperOpen(false); setCreatePaperTemplate(null); setEditingPaper(null); }}
                    onSaved={() => { fetchData(); setActiveTab('saved_papers'); }}
                    user={user}
                    existingPaper={editingPaper}
                />
            )}
        </div>
    );
}

export function ExamTemplatesPage() {
    return <ErrorBoundary><ExamTemplatesPageInner /></ErrorBoundary>;
}