name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Platane/snk@v3
        with:
          github_user_name: vkmnamit
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-game.svg
            dist/github-contribution-grid-snake-game-dark.svg?palette=github-dark

      - run: git diff --exit-code || echo "Changes detected"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake game"
          file_pattern: "dist/*.svg"